### ISSUE TITLE
cannot import name 'AutoImageClassifier'

### ISSUE THREAD

**Issue by zh-my** [gradsflow/gradsflow#132] opened 2021-12-02 07:01 UTC
When I use "from gradsflow import AutoImageClassifier"
bug: cannot import name 'AutoImageClassifier'

**Comment by aniketmaurya** [comment] 2021-12-02 09:35
hi @zh-my, thanks for reporting this issue. May I know which Gradsflow version are you using?

**Comment by aniketmaurya** [comment] 2021-12-15 06:00
Closing this since this issue is not reproducible. Feel free to open the issue if you are still facing this issue.
Thanks

**Closed by aniketmaurya** 2021-12-15 06:00 UTC
